# Generated by Django 5.1.1 on 2024-09-09 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_app', '0004_alter_user_groups_alter_user_user_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentaccount',
            name='users',
        ),
        migrations.AlterField(
            model_name='accountmembership',
            name='role',
            field=models.CharField(choices=[('view', 'View'), ('post', 'Post'), ('crud', 'CRUD')], max_length=4),
        ),
        migrations.AlterField(
            model_name='investmentaccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investment_app.investmentaccount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
