name: Run Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Print Python version
        run: python --version

      - name: Print Pip version
        run: pip --version

      - name: List installed packages
        run: pip list

      - name: Run Django Migrations
        env:
          DJANGO_SETTINGS_MODULE: inverstment.settings  # Adjust to your Django settings module
        run: |
          python manage.py migrate

      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE inverstment.settings  # Adjust to your Django settings module
        run: |
          pytest --maxfail=1 --disable-warnings -q
